// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pes-wheel/PesWheel.tsx": () => import("../components/mockups/pes-wheel/PesWheel.tsx")
};
